### ISSUE TITLE
Problem with authorizing Google Photos

### ISSUE THREAD

**Issue by ernicek** [mrworf/photoframe#103]
When I tried to authorize Google Photos (I used the steps from the WIKI page), at the end (I mean after I choose the account and then I allow the sensenet.nu to access my Photos) I saw this "internal" error:

URL in the browser: http://192.168.1.67:7777/callback?state=51828227394efa514fa3bbefa9a78c4e-192.168.1.67-95191d54a1462f750b6e99469150adc68267404e&code=4/jwH1UegTS4PlnWH_oGPO2KPDjtjSfYPDCxUTNN79OWGTNBQvneNs6QiPjz1f33Lb4ox6fpKF9zf-8XhNAvC3sWA

Traceback (most recent call last):
  ```
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "./frame.py", line 472, in oauth_callback
    if services.oauthCallback(request):
  File "/root/photoframe/modules/servicemanager.py", line 169, in oauthCallback
    svc.finishOAuth(request.url)
  File "/root/photoframe/services/base.py", line 243, in finishOAuth
    self._OAUTH.complete(url)
  File "/root/photoframe/modules/oauth.py", line 126, in complete
    client_secret=self.oauth['client_secret'],
KeyError: 'client_secret'

```
Please could you help me?

**Comment by ernicek** [comment]
Just adding a log

[debug.zip](https://github.com/mrworf/photoframe/files/3416968/debug.zip)

**Comment by mrworf** [comment]
Hmm.. odd, the client_secret field is missing, do you have any odd extensions in your browser? Could you turn off any non-default extensions and try again?

**Comment by ernicek** [comment]
Wow! Thank you! I just used another browser (Safari) and it works! So, thank you!
