### ISSUE TITLE
Cannot Authorize Google Photos

### ISSUE THREAD

**Issue by jkbailmeout** [mrworf/photoframe#116]
I'm attempting to authorize GooglePhotos that was added and I receive the below error message.  I followed the directions for setting up the project, adding the API, and adding the credentials prior to downloading the JSON file.  

Uh oh, something went wrong...
Please go to github and see if this is a known issue, if not, feel free to file a new issue with the following information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "./frame.py", line 517, in service_link
    return redirect(services.oauthStart(service))
  File "/root/photoframe/modules/servicemanager.py", line 182, in oauthStart
    return svc.startOAuth()
  File "/root/photoframe/services/base.py", line 239, in startOAuth
    return self._OAUTH.initiate()
  File "/root/photoframe/modules/oauth.py", line 106, in initiate
    self.rid = self.getRedirectId()
  File "/root/photoframe/modules/oauth.py", line 102, in getRedirectId
    r = requests.get('%s/?register' % self.ridURI)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='photoframe.sensenet.nu', port=443): Max retries exceeded with url: /?register (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))
Thank you for your patience

**Comment by mrworf** [comment]
Should work again
