### ISSUE TITLE
Issue when trying to upload json

### ISSUE THREAD

**Issue by IberianSoldierPC** [mrworf/photoframe#132]
Hi! When I try to upload the json file this debug pops up:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/photoframe/routes/baseroute.py", line 62, in __call__
    return self.handle(self.app, **kwargs)
  File "/root/photoframe/routes/oauthlink.py", line 44, in handle
    return self.redirect(self.servicemgr.oauthStart(kwargs['service']))
  File "/root/photoframe/modules/servicemanager.py", line 190, in oauthStart
    return svc.startOAuth()
  File "/root/photoframe/services/base.py", line 257, in startOAuth
    return self._OAUTH.initiate()
  File "/root/photoframe/modules/oauth.py", line 119, in initiate
    self.rid = self.getRedirectId()
  File "/root/photoframe/modules/oauth.py", line 115, in getRedirectId
    r = requests.get('%s/?register' % self.ridURI)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='photoframe.sensenet.nu', port=443): Max retries exceeded with url: /?register (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))

What's the issue? Thank you in advance

**Comment by mrworf** [comment]
This would indicate that your RPi is unable to connect to https://photoframe.sensenet.nu ... Can you make sure it works from your browser first? It will redirect you to github but that means it's working 😄

**Comment by P43082** [comment]
I cannot get to this site on my browser or phone on cell service. Is it down for everyone? When I checked isitdownrightnow.com it shows down as well.

**Comment by mrworf** [comment]
My apologies, due to the recent PG&E Public Safety Power Shutoff, my server went down and didn't start properly once power was returned. It's running now and I'm learning about how systemd can autorestart crashed services

(in case anyone wonders about this issue, my NGINX instance started before DNS was available, causing it to exit with an error)

**Comment by mrworf** [comment]
(And for those wondering, it now will restart nginx if it ever fails, also waits for bind9 to be online before starting)
