### ISSUE TITLE
Goes too slow

### ISSUE THREAD

**Issue by georgeoftown** [mrworf/photoframe#151]
**Running version**
```
commit 760b8754256e13a35096517c2bb0fd9801ea1c43
Author: Henric Andersson 
Date:   Fri Nov 15 21:47:13 2019 -0800

    Handle empty albums (#143)
    
    Soemtimes an album may show up as empty and due to caching it will
    never be queried again. This change forces a refresh every X minute
    even if it was empty before
    
    Fix #140

On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```
**Last 100 lines from the photoframe log**
```
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:10 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:37:14 Sol-Eladio photoframe[427]: Traceback (most recent call last):
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:14 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:37:17 Sol-Eladio photoframe[427]: Traceback (most recent call last):
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:17 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:37:20 Sol-Eladio photoframe[427]: Traceback (most recent call last):
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:20 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:37:24 Sol-Eladio photoframe[427]: Traceback (most recent call last):
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:24 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:37:27 Sol-Eladio photoframe[427]: Traceback (most recent call last):
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:27 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:39:39 Sol-Eladio photoframe[427]: 2020-02-14 14:39:39,238 - INFO - Processing /mnt/usb1/photoframe/IMG_3700.JPG
Feb 14 14:39:39 Sol-Eladio photoframe[427]: 2020-02-14 14:39:39,726 - INFO - Change of configuration, flush data and restart
Feb 14 14:39:39 Sol-Eladio photoframe[427]: 2020-02-14 14:39:39,736 - INFO - '/root/cache/' has been emptied
Feb 14 14:42:44 Sol-Eladio photoframe[427]: 2020-02-14 14:42:44,097 - INFO - Processing /mnt/usb1/photoframe/bbbb2019-12-31_051011.jpg
Feb 14 14:45:50 Sol-Eladio photoframe[427]: 2020-02-14 14:45:50,634 - INFO - Processing /mnt/usb1/photoframe/bb2019-12-31_045409.jpg
Feb 14 14:49:09 Sol-Eladio photoframe[427]: 2020-02-14 14:49:09,518 - INFO - Processing /mnt/usb1/photoframe/bIMG_2778.jpg
```
(size of logfile 5483775 bytes, created Fri Feb 14 14:49:09 2020)
Last 100 lines from the system log (/var/log/syslog)
```
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:10 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:10 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:10 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:37:14 Sol-Eladio photoframe[427]: Traceback (most recent call last):
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:14 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:14 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:14 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:37:17 Sol-Eladio photoframe[427]: Traceback (most recent call last):
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:17 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:17 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:17 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:37:20 Sol-Eladio photoframe[427]: Traceback (most recent call last):
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:20 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:20 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:20 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:37:24 Sol-Eladio photoframe[427]: Traceback (most recent call last):
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:24 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:24 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:24 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:37:27 Sol-Eladio photoframe[427]: Traceback (most recent call last):
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.process_request(request, client_address)
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.finish_request(request, client_address)
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.RequestHandlerClass(request, client_address, self)
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.finish()
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.wfile.close()
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self.flush()
Feb 14 14:37:27 Sol-Eladio photoframe[427]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Feb 14 14:37:27 Sol-Eladio photoframe[427]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Feb 14 14:37:27 Sol-Eladio photoframe[427]: error: [Errno 32] Broken pipe
Feb 14 14:39:39 Sol-Eladio photoframe[427]: 2020-02-14 14:39:39,238 - INFO - Processing /mnt/usb1/photoframe/IMG_3700.JPG
Feb 14 14:39:39 Sol-Eladio photoframe[427]: 2020-02-14 14:39:39,726 - INFO - Change of configuration, flush data and restart
Feb 14 14:39:39 Sol-Eladio photoframe[427]: 2020-02-14 14:39:39,736 - INFO - '/root/cache/' has been emptied
Feb 14 14:42:44 Sol-Eladio photoframe[427]: 2020-02-14 14:42:44,097 - INFO - Processing /mnt/usb1/photoframe/bbbb2019-12-31_051011.jpg
Feb 14 14:45:50 Sol-Eladio photoframe[427]: 2020-02-14 14:45:50,634 - INFO - Processing /mnt/usb1/photoframe/bb2019-12-31_045409.jpg
Feb 14 14:49:09 Sol-Eladio photoframe[427]: 2020-02-14 14:49:09,518 - INFO - Processing /mnt/usb1/photoframe/bIMG_2778.jpg
```
(size of logfile 5483775 bytes, created Fri Feb 14 14:49:09 2020)
**Stacktrace of all running threads**
```
# ThreadID: -1247005584
File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  self.run()
File: "/usr/lib/python2.7/threading.py", line 754, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/root/photoframe/modules/slideshow.py", line 312, in presentation
  result = self.services.servicePrepareNextItem(self.settings.get('tempfolder'), self.supportedFormats, displaySize, randomize)
File: "/root/photoframe/modules/servicemanager.py", line 410, in servicePrepareNextItem
  result = svc.prepareNextItem(destinationDir, supportedMimeTypes, displaySize, randomize)
File: "/root/photoframe/services/base.py", line 420, in prepareNextItem
  result = self.selectImageFromAlbum(destinationFile, supportedMimeTypes, displaySize, randomize)
File: "/root/photoframe/services/svc_usb.py", line 282, in selectImageFromAlbum
  result = BaseService.selectImageFromAlbum(self, destinationDir, supportedMimeTypes, displaySize, randomize)
File: "/root/photoframe/services/base.py", line 483, in selectImageFromAlbum
  images = self.getImagesFor(keyword)
File: "/root/photoframe/services/svc_usb.py", line 297, in getImagesFor
  images = self.getAlbumInfo(self.baseDir, files)
File: "/root/photoframe/services/svc_usb.py", line 310, in getAlbumInfo
  dim = helper.getImageSize(fullFilename)
File: "/root/photoframe/modules/helper.py", line 163, in getImageSize
  output = subprocess.check_output(['/usr/bin/identify', filename], stderr=void)
File: "/usr/lib/python2.7/subprocess.py", line 213, in check_output
  output, unused_err = process.communicate()
File: "/usr/lib/python2.7/subprocess.py", line 471, in communicate
  stdout = _eintr_retry_call(self.stdout.read)
File: "/usr/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
  return func(*args)

# ThreadID: -1267731344
File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  self.run()
File: "/root/photoframe/modules/shutdown.py", line 59, in run
  i = poller.poll(None)

# ThreadID: -1257245584
File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  self.run()
File: "/root/photoframe/modules/timekeeper.py", line 118, in run
  time.sleep(60) # every minute

# ThreadID: -1225080832
File: "./frame.py", line 178, in 
  frame.start()
File: "./frame.py", line 175, in start
  self.webServer.start()
File: "/root/photoframe/modules/server.py", line 84, in start
  self.run()
File: "/root/photoframe/modules/server.py", line 101, in run
  self.app.run(debug=False, port=self.port, host=self.listen )
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 841, in run
  run_simple(host, port, self, **options)
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 708, in run_simple
  inner()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 673, in inner
  srv.serve_forever()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 511, in serve_forever
  HTTPServer.serve_forever(self)
File: "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
  self._handle_request_noblock()
File: "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
  self.process_request(request, client_address)
File: "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
  self.finish_request(request, client_address)
File: "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
  self.RequestHandlerClass(request, client_address, self)
File: "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
  self.handle()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 228, in handle
  rv = BaseHTTPRequestHandler.handle(self)
File: "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
  self.handle_one_request()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 263, in handle_one_request
  return self.run_wsgi()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
  execute(self.server.app)
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in execute
  application_iter = app(environ, start_response)
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
  return self.wsgi_app(environ, start_response)
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
  response = self.full_dispatch_request()
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
  rv = self.dispatch_request()
File: "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
File: "/root/photoframe/routes/baseroute.py", line 62, in __call__
  return self.handle(self.app, **kwargs)
File: "/root/photoframe/routes/debug.py", line 34, in handle
  report.append(debug.stacktrace())
File: "/root/photoframe/modules/debug.py", line 48, in stacktrace
  for filename, lineno, name, line in traceback.extract_stack(stack):
```

**Comment by mrworf** [comment]
What goes too slow? Time?

**Comment by georgeoftown** [comment]
The raspberry pi zero died you can close
