### ISSUE TITLE
Failed to get photos from Googlephoto

### ISSUE THREAD

**Issue by key5000** [mrworf/photoframe#164]
Hello,
I'm trying to setup a new photo frame on Raspberry PI, the process went smooth until loading the JASON file from Google API, there is the error that I get, could you please help.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "./frame.py", line 455, in service_link
    return redirect(services.oauthStart(service))
  File "/root/photoframe/modules/servicemanager.py", line 144, in oauthStart
    return svc.startOAuth()
  File "/root/photoframe/services/base.py", line 191, in startOAuth
    return self._OAUTH.initiate()
  File "/root/photoframe/modules/oauth.py", line 106, in initiate
    self.rid = self.getRedirectId()
  File "/root/photoframe/modules/oauth.py", line 102, in getRedirectId
    r = requests.get('%s/?register' % self.ridURI)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)

**Comment by mrworf** [comment]
Closing this ticket due to inactivity. But typically this is caused by time and date being wrong on the raspberry pi
