### ISSUE TITLE
Photoframe process dies just after startup with KeyError: 'width' error

### ISSUE THREAD

**Issue by rafik24** [mrworf/photoframe#169]
Hi Mrworf,

My newly setup frame dies on startup complaining it could not find the width of a picture (My 10 thousands feet analysis due to poor knowledge of Python).

here are the debug logs:

./frame.py --debug
2020-11-25 09:47:38,303 - INFO - Loading service USB_Photos from svc_usb.py
2020-11-25 09:47:38,304 - INFO - Loading service PicasaWeb from svc_picasaweb.py
2020-11-25 09:47:38,306 - INFO - Loading service GooglePhotos from svc_googlephotos.py
2020-11-25 09:47:38,307 - INFO - Loading service SimpleUrl from svc_simpleurl.py
2020-11-25 09:47:38,310 - INFO - ColorSensor not available
2020-11-25 09:47:38,311 - DEBUG - Adding listener <bound method display.enable of <modules.display.display instance at 0x75c80e90>>
2020-11-25 09:47:38,312 - INFO - GPIO shutdown can be triggered by GPIO 26
2020-11-25 09:47:38,314 - INFO - Cache is set to True
2020-11-25 09:47:38,315 - DEBUG - hourOn = 4, hourOff = 22
2020-11-25 09:47:38,315 - DEBUG - Powermode changed to 'none'
2020-11-25 09:47:38,316 - DEBUG - Adding listener <bound method slideshow.shouldShow of <modules.slideshow.slideshow instance at 0x75c99e90>>
2020-11-25 09:47:38,320 - DEBUG - Found "/boot/http-auth.json", loading the data
2020-11-25 09:47:38,324 - INFO - Registering URL /options/<cmd> to RouteOptions (simple)
2020-11-25 09:47:38,326 - INFO - Registering URL /options/<cmd>/<arg> to RouteOptions (simple)
2020-11-25 09:47:38,331 - INFO - Registering URL /<path:file> to RoutePages (simple)
2020-11-25 09:47:38,332 - INFO - Registering URL / to RoutePages (simple)
2020-11-25 09:47:38,336 - INFO - Registering URL /debug to RouteDebug (simple)
2020-11-25 09:47:38,339 - INFO - Registering URL /setting to RouteSettings
2020-11-25 09:47:38,341 - INFO - Registering URL /setting/<key> to RouteSettings
2020-11-25 09:47:38,343 - INFO - Registering URL /setting/<key>/<value> to RouteSettings
2020-11-25 09:47:38,345 - INFO - Registering URL /keywords/<service>/help to RouteKeywords
2020-11-25 09:47:38,347 - INFO - Registering URL /keywords/<service> to RouteKeywords
2020-11-25 09:47:38,349 - INFO - Registering URL /keywords/<service>/add to RouteKeywords
2020-11-25 09:47:38,351 - INFO - Registering URL /keywords/<service>/delete to RouteKeywords
2020-11-25 09:47:38,353 - INFO - Registering URL /keywords/<service>/source/<int:index> to RouteKeywords
2020-11-25 09:47:38,356 - INFO - Registering URL /keywords/<service>/details/<int:index> to RouteKeywords
2020-11-25 09:47:38,359 - INFO - Registering URL /rotation to RouteOrientation
2020-11-25 09:47:38,360 - INFO - Registering URL /rotation/<int:orient> to RouteOrientation
2020-11-25 09:47:38,362 - INFO - Registering URL /overscan to RouteOverscan
2020-11-25 09:47:38,364 - INFO - Registering URL /overscan/<overscan> to RouteOverscan
2020-11-25 09:47:38,366 - INFO - Registering URL /maintenance/<cmd> to RouteMaintenance
2020-11-25 09:47:38,368 - INFO - Registering URL /details/<about> to RouteDetails
2020-11-25 09:47:38,370 - INFO - Registering URL /upload/<item> to RouteUpload
2020-11-25 09:47:38,372 - INFO - Registering URL /callback to RouteOAuthLink
2020-11-25 09:47:38,375 - INFO - Registering URL /service/<service>/link to RouteOAuthLink
2020-11-25 09:47:38,377 - INFO - Registering URL /service/<service>/oauth to RouteOAuthLink
2020-11-25 09:47:38,379 - INFO - Registering URL /service/<action> to RouteService
2020-11-25 09:47:38,381 - INFO - Registering URL /control/<cmd> to RouteControl
2020-11-25 09:47:38,383 - INFO - Registering URL /events to RouteEvents
2020-11-25 09:47:38,385 - INFO - Registering URL /events/<int:since> to RouteEvents
2020-11-25 09:47:38,386 - INFO - Registering URL /events/remove/<int:id> to RouteEvents
2020-11-25 09:47:39,467 - DEBUG - Keywords either not scanned or we need to scan now
2020-11-25 09:47:39,729 - DEBUG - Keywords either not scanned or we need to scan now
2020-11-25 09:47:39,926 - DEBUG - Keywords either not scanned or we need to scan now
2020-11-25 09:47:40,193 - DEBUG - Keywords either not scanned or we need to scan now
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/photoframe/modules/slideshow.py", line 268, in presentation
    self.services.getServices(readyOnly=True)
  File "/root/photoframe/modules/servicemanager.py", line 352, in getServices
    if readyOnly and self.getServiceState(k) != BaseService.STATE_READY:
  File "/root/photoframe/modules/servicemanager.py", line 289, in getServiceState
    return svc.updateState()
  File "/root/photoframe/services/base.py", line 140, in updateState
    elif self.getImagesTotal() == 0:
  File "/root/photoframe/services/base.py", line 185, in getImagesTotal
    self._getImagesFor(keyword) # Will make sure to get images
  File "/root/photoframe/services/base.py", line 449, in _getImagesFor
    images = self.getImagesFor(keyword)
  File "/root/photoframe/services/svc_googlephotos.py", line 374, in getImagesFor
    return self.parseAlbumInfo(albumdata, keyword)
  File "/root/photoframe/services/svc_googlephotos.py", line 385, in parseAlbumInfo
    item.setDimensions(entry['mediaMetadata']['width'], entry['mediaMetadata']['height'])
KeyError: 'width'

Could you please help so I can figure out what is going on / identify the piture that comes back without width and log the error and carry on or else to cater for this use case ?

Thank in advance,
Rafik

**Comment by mrworf** [comment]
Closing this ticket due to age
