### ISSUE TITLE
Google Authorisation failed 

### ISSUE THREAD

**Issue by mnkypshngbttns** [mrworf/photoframe#208]
Reflashed SD Card and started fresh. But now when trying to authorise google photos with client secret json file get

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/photoframe/routes/baseroute.py", line 62, in __call__
    return self.handle(self.app, **kwargs)
  File "/root/photoframe/routes/oauthlink.py", line 44, in handle
    return self.redirect(self.servicemgr.oauthStart(kwargs['service']))
  File "/root/photoframe/modules/servicemanager.py", line 199, in oauthStart
    return svc.startOAuth()
  File "/root/photoframe/services/base.py", line 274, in startOAuth
    return self._OAUTH.initiate()
  File "/root/photoframe/modules/oauth.py", line 122, in initiate
    self.rid = self.getRedirectId()
  File "/root/photoframe/modules/oauth.py", line 118, in getRedirectId
    r = requests.get('%s/?register' % self.ridURI)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

**Comment by shermanpark** [comment]
I am having the exact same issue. Maybe it has something to do with Google enabling 2-factor authentication?

**Comment by mnkypshngbttns** [comment]
hopefully Henric can come up with a solution soon. I miss my photoframe

**Comment by mrworf** [comment]
It should work now. I hadn't gotten around to uploading my renewed certificate, which caused photoframe.sensenet.nu (needed for the OAuth path) not to validate anymore. 

Sorry about this. Please re-open if this is still an issue (OpenSSL indicates it should be resolved).

**Comment by mnkypshngbttns** [comment]
Thanks Henric! Confirmed working still hopefully this will fix the need to reauthorise every few weeks too?

**Comment by mrworf** [comment]
That's unrelated, this issue with ssl started this week due to certificate expiration date. The other issue will remain. Hopefully I get some time over the holidays to look at this closer.
