### ISSUE TITLE
GooglePhotos Auth file not working

### ISSUE THREAD

**Issue by ashinckley** [mrworf/photoframe#211]
I've gone through the [wiki](https://github.com/mrworf/photoframe/wiki/How-to-create-an-authorization-file) process in setting up the GooglePhotos API at least 3 times now.  Each time I get the same result, after I upload the .json file it hangs for a few minutes and provides the following error.  See below.  While the API instructions are slightly outdated, I think I followed the process as well as I could. There might be some new step or process I'm missing.  

"Uh oh, something went wrong...
Please go to [github](https://github.com/mrworf/photoframe/issues) and see if this is a known issue, if not, feel free to file a [new issue](https://github.com/mrworf/photoframe/issues/new) with the following information:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/photoframe/routes/baseroute.py", line 62, in __call__
    return self.handle(self.app, **kwargs)
  File "/root/photoframe/routes/oauthlink.py", line 44, in handle
    return self.redirect(self.servicemgr.oauthStart(kwargs['service']))
  File "/root/photoframe/modules/servicemanager.py", line 199, in oauthStart
    return svc.startOAuth()
  File "/root/photoframe/services/base.py", line 274, in startOAuth
    return self._OAUTH.initiate()
  File "/root/photoframe/modules/oauth.py", line 122, in initiate
    self.rid = self.getRedirectId()
  File "/root/photoframe/modules/oauth.py", line 118, in getRedirectId
    r = requests.get('%s/?register' % self.ridURI)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='photoframe.sensenet.nu', port=443): Max retries exceeded with url: /?register (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out',))`

**Comment by mrworf** [comment]
Hi,

Sorry about that, in the middle of an ISP change and the DNS records 
haven't propagated yet. Should work within the next 24hrs.

/Henric

On 2023-06-04 19:38, ashinckley wrote:

> I've gone through the wiki [1] process in setting up the GooglePhotos 
> API at least 3 times now. Each time I get the same result, after I 
> upload the .json file it hangs for a few minutes and provides the 
> following error. See below. While the API instructions are slightly 
> outdated, I think I followed the process as well as I could. There 
> might be some new step or process I'm missing.
> 
> "Uh oh, something went wrong...
> Please go to github [2] and see if this is a known issue, if not, feel 
> free to file a new issue [3] with the following information:
> Traceback (most recent call last): File 
> "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in 
> full_dispatch_request rv = self.dispatch_request() File 
> "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in 
> dispatch_request return 
> self.view_functions[rule.endpoint](**req.view_args) File 
> "/root/photoframe/routes/baseroute.py", line 62, in __call__ return 
> self.handle(self.app, **kwargs) File 
> "/root/photoframe/routes/oauthlink.py", line 44, in handle return 
> self.redirect(self.servicemgr.oauthStart(kwargs['service'])) File 
> "/root/photoframe/modules/servicemanager.py", line 199, in oauthStart 
> return svc.startOAuth() File "/root/photoframe/services/base.py", line 
> 274, in startOAuth return self._OAUTH.initiate() File 
> "/root/photoframe/modules/oauth.py", line 122, in initiate self.rid = 
> self.getRedirectId() File "/root/photoframe/modules/oauth.py", line 
> 118, in getRedirectId r = requests.get('%s/?register' % self.ridURI) 
> File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in 
> get return request('get', url, params=params, **kwargs) File 
> "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request 
> return session.request(method=method, url=url, **kwargs) File 
> "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in 
> request resp = self.send(prep, **send_kwargs) File 
> "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in 
> send r = adapter.send(request, **kwargs) File 
> "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in 
> send raise ConnectionError(e, request=request) ConnectionError: 
> HTTPSConnectionPool(host='photoframe.sensenet.nu', port=443): Max 
> retries exceeded with url: /?register (Caused by NewConnectionError(': 
> Failed to establish a new connection: [Errno 110] Connection timed 
> out',))
> 
> --
> Reply to this email directly, view it on GitHub [4], or unsubscribe 
> [5].
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>


Links:
------
[1] 
https://github.com/mrworf/photoframe/wiki/How-to-create-an-authorization-file
[2] https://github.com/mrworf/photoframe/issues
[3] https://github.com/mrworf/photoframe/issues/new
[4] https://github.com/mrworf/photoframe/issues/211
[5]

**Comment by mrworf** [comment]
Should be working now


------ Original Message ------
From "Henric Andersson" ***@***.***>
To "mrworf/photoframe" 
***@***.***>
Date 6/5/2023 8:05:41 AM
Subject Re: [mrworf/photoframe] GooglePhotos Auth file not working 
(Issue #211)

**Comment by ashinckley** [comment]
Thanks for looking into this.  I seem to get further into the process now. 
I now get the Google error:
`You can’t sign in because this app sent an invalid request. You can try again later, or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch`

I suspect this might be something on my end in following the wiki, or maybe Google has changed the process to be a bit different.

**Comment by ashinckley** [comment]
In my attempts to change things up, I added the following to my Authorized redirect URIs:

http://photoframe.sensenet.nu
https://photoframe.sensenet.nu
http://www.photoframe.sensenet.nu
https://www.photoframe.sensenet.nu

Something changed.  I now get to a Google login screen, but when I select my account I get the following error:

`
Access blocked: sensenet.nu has not completed the Google verification process
**My email account address here**
sensenet.nu has not completed the Google verification process. The app is currently being tested, and can only be accessed by [developer](https://accounts.google.com/)-approved testers. If you think you should have access, contact the developer.
If you are a developer of sensenet.nu, see [error details](https://accounts.google.com/).
Error 403: access_denied
`

**Comment by ashinckley** [comment]
@mrworf Thanks for the updates and the effort to keep this project going.
I went through the new 2025 wiki page and started over from scratch.  Still didn't work for me.  I got this error after the step "Linking the photoframe using the authorization file" and clicking "Authorize"

> Uh oh, something went wrong...
Please go to [github](https://github.com/mrworf/photoframe/issues) and see if this is a known issue, if not, feel free to file a [new issue](https://github.com/mrworf/photoframe/issues/new) with the following information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "./frame.py", line 455, in service_link
    return redirect(services.oauthStart(service))
  File "/root/photoframe/modules/servicemanager.py", line 144, in oauthStart
    return svc.startOAuth()
  File "/root/photoframe/services/base.py", line 191, in startOAuth
    return self._OAUTH.initiate()
  File "/root/photoframe/modules/oauth.py", line 106, in initiate
    self.rid = self.getRedirectId()
  File "/root/photoframe/modules/oauth.py", line 102, in getRedirectId
    r = requests.get('%s/?register' % self.ridURI)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

>
