### ISSUE TITLE
Photoframe not Authorizing

### ISSUE THREAD

**Issue by weinsteing** [mrworf/photoframe#214]
Hi there, your usually excellent and reliable photoframe software has not been working for more than 1 week now.  This is very frustrating.

I seen your messages to others saying it is up and running, however I can assure you it is not for me in the UK.  Please take a look at what may be the problem.  Could it be to do with the JSON file?  If so then how do I regenerate it?  If not, then what else is it?

Thanks and regards ... Gary

Uh oh, something went wrong...
Please go to [github](https://github.com/mrworf/photoframe/issues) and see if this is a known issue, if not, feel free to file a [new issue](https://github.com/mrworf/photoframe/issues/new) with the following information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/photoframe/routes/baseroute.py", line 62, in __call__
    return self.handle(self.app, **kwargs)
  File "/root/photoframe/routes/oauthlink.py", line 44, in handle
    return self.redirect(self.servicemgr.oauthStart(kwargs['service']))
  File "/root/photoframe/modules/servicemanager.py", line 199, in oauthStart
    return svc.startOAuth()
  File "/root/photoframe/services/base.py", line 274, in startOAuth
    return self._OAUTH.initiate()
  File "/root/photoframe/modules/oauth.py", line 122, in initiate
    self.rid = self.getRedirectId()
  File "/root/photoframe/modules/oauth.py", line 118, in getRedirectId
    r = requests.get('%s/?register' % self.ridURI)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='photoframe.sensenet.nu', port=443): Max retries exceeded with url: /?register (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by mrworf** [comment]
I agree, it looked like it all worked, but apparently my ISP changed IP on me during the week and the haproxy in OPNsense didn't catch that. I'm working on a monitoring system now so I can be alerted and take appropriate action. 

But I just confirmed and it should work now (again). 

Sorry for all the trouble.

**Comment by weinsteing** [comment]
Henric, thank you. I can confirm the frame is working again.

Thanks and regards Gary

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Meron0th** [comment]
Hello! Been loving the project in my home, but I've been having this exact issue as well recently
