### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by hermy65** [mrworf/photoframe#22]
Just went through your setup guide twice and each time after i paste the OAUTH data and click the connect button i get this:

Uh oh, something went wrong...
Please go to github and see if this is a known issue, if not, feel free to file a new issue with the following information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "./frame.py", line 414, in oauth_step1
    return redirect(oauth.initiate())
  File "/root/photoframe/modules/oauth.py", line 89, in initiate
    self.rid = self.getRedirectId()
  File "/root/photoframe/modules/oauth.py", line 85, in getRedirectId
    r = requests.get('%s/?register' % self.ridURI)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='photoframe.sensenet.nu', port=443): Max retries exceeded with url: /?register (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by mrworf** [comment]
Try again, been having issues with my ISP so the network service was down, it should all work now.

**Comment by mrworf** [comment]
Closing this due to no updates. Please reopen if still an issue
