### ISSUE TITLE
Error after OKing sensenet to access google photos

### ISSUE THREAD

**Issue by hgrinolds** [mrworf/photoframe#27]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "./frame.py", line 419, in oauth_step3
    oauth.complete(request.url)
  File "/root/photoframe/modules/oauth.py", line 109, in complete
    client_secret=self.oauth['client_secret'],
KeyError: 'client_secret'

**Comment by mrworf** [comment]
This would indicate that you didn't copy all data (or perhaps the wrong) data into the OAuth setup for photoframe.

**Comment by hgrinolds** [comment]
OK,  thank you for responding.  Is there anyway to get back to auth input without reloading the code into Pi?

Hugh

________________________________

**Comment by hgrinolds** [comment]
Thank you for the information.   It all is up and running now and I am working on getting photos to fit or stretch to the display and filter the access for the photos.   Nice use of Raspberry Pi.  Thank you for the sketch.

Hugh
