### ISSUE TITLE
Wired configuration

### ISSUE THREAD

**Issue by allygillespie** [mrworf/photoframe#77]
Hi, can you use this whilst connected vi ethernet cable?

I have followed all the steps but am getting the following error...

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "./frame.py", line 410, in oauth_callback
    if services.oauthCallback(request):
  File "/root/photoframe/modules/servicemanager.py", line 131, in oauthCallback
    svc.finishOAuth(request.url)
  File "/root/photoframe/services/base.py", line 195, in finishOAuth
    self._OAUTH.complete(url)
  File "/root/photoframe/modules/oauth.py", line 127, in complete
    authorization_response=url)
  File "/usr/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 221, in fetch_token
    verify=verify, proxies=proxies)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 358, in request
    headers=headers, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)`

Any help would be appreciated.

Thank you

**Comment by mrworf** [comment]
Yes, wired or wireless does not make a difference. Which service were you trying to connect with? Please be advised that Picasa Web is going away (Google is deprecating it) so if that's what you tried, please retry with Google Photos instead.

**Comment by allygillespie** [comment]
Thank you for the response.
I was trying with Google Photos. Followed all the steps - twice, very strange.
When I auth, I sign in with my google and grant permission, that’s when the error comes up.
I will have to try again.
